# Generated by Django 5.0.6 on 2024-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_metadata_delete_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='form',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
