# Generated by Django 5.0.6 on 2024-08-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_email_alter_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
